#print("Hello World!")
#print("hello Again")
#print("I like typing this.")
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
print('Ze will tell me to stop laughing now.')